token = "1246903350:AAEU9XSi7GIoNVsXQjMe6UTSzzpjSIRP7Ls"


weather_list = {"новосибирск": "https://yandex.ru/pogoda/novosibirsk", "екатеринбург": "https://yandex.ru/pogoda/yekaterinburg",
                "нижний новгород": "https://yandex.ru/pogoda/47", "самара": "https://yandex.ru/pogoda/samara",
                "казань": "https://yandex.ru/pogoda/kazan", "челябинск": "https://yandex.ru/pogoda/chelyabinsk",
                "омск": "https://yandex.ru/pogoda/omsk", "ростов-на-дону": "https://yandex.ru/pogoda/rostov-na-donu",
                "красноярск": "https://yandex.ru/pogoda/krasnoyarsk", "пермь": "https://yandex.ru/pogoda/perm",
                "волгоград": "https://yandex.ru/pogoda/volgograd", "киев": "https://yandex.ru/pogoda/kyiv",
                "харьков": "https://yandex.ru/pogoda/kharkiv", "одесса": "https://yandex.ru/pogoda/odessa",
                "донецк": "https://yandex.ru/pogoda/142", "луганск": "https://yandex.ru/pogoda/luhansk",
                "минск": "https://yandex.ru/pogoda/minsk", "таллин": "https://yandex.ru/pogoda/tallinn",
                "рига": "https://yandex.ru/pogoda/riga", "вильнюс": "https://yandex.ru/pogoda/vilnius",
                "варшава": "https://yandex.ru/pogoda/warsaw", "прага": "https://yandex.ru/pogoda/prague",
                "хельсинки": "https://yandex.ru/pogoda/10493", "стокгольм": "https://yandex.ru/pogoda/10519",
                "осло": "https://yandex.ru/pogoda/oslo", "берлин": "https://yandex.ru/pogoda/berlin",
                "лейпциг": "https://yandex.ru/pogoda/10410", "дрезден": "https://yandex.ru/pogoda/dresden",
                "мюнхен": "https://yandex.ru/pogoda/99", "штутгарт": "https://yandex.ru/pogoda/stuttgart",
                "дюссельдорф": "https://yandex.ru/pogoda/10408", "франкфурт": "https://yandex.ru/pogoda/frankfurt-am-main",
                "гамбург": "https://yandex.ru/pogoda/hamburg", "вена": "https://yandex.ru/pogoda/vienna",
                "зальцбург": "https://yandex.ru/pogoda/salzburg", "цюрих": "https://yandex.ru/pogoda/zurich",
                "берн": "https://yandex.ru/pogoda/bern", "милан": "https://yandex.ru/pogoda/milan",
                "турин": "https://yandex.ru/pogoda/10449", "венеция": "https://yandex.ru/pogoda/venice",
                "флоренция": "https://yandex.ru/pogoda/10461", "рим": "https://yandex.ru/pogoda/10445",
                "неаполь": "https://yandex.ru/pogoda/naples-italy", "париж": "https://yandex.ru/pogoda/10502",
                "амстердам": "https://yandex.ru/pogoda/10466", "мадрид": "https://yandex.ru/pogoda/madrid",
                "барселона": "https://yandex.ru/pogoda/barcelona", "лондон": "https://yandex.ru/pogoda/london",
                "дублин": "https://yandex.ru/pogoda/dublin", "нью-йорк": "https://yandex.ru/pogoda/new-york",
                "майами": "https://yandex.ru/pogoda/10122", "хьюстон": "https://yandex.ru/pogoda/houston",
                "даллас": "https://yandex.ru/pogoda/dallas", "лос-анджелес": "https://yandex.ru/pogoda/los-angeles",
                "сан-франциско": "https://yandex.ru/pogoda/san-francisco", "сиэтл": "https://yandex.ru/pogoda/seattle",
                "ванкувер": "https://yandex.ru/pogoda/21353", "оттава": "https://yandex.ru/pogoda/10114",
                "токио": "https://yandex.ru/pogoda/tokyo", "сеул": "https://yandex.ru/pogoda/10635",
                "пекин": "https://yandex.ru/pogoda/beijing", "шанхай": "https://yandex.ru/pogoda/shanghai",
                "гонконг": "https://yandex.ru/pogoda/11514", "сидней": "https://yandex.ru/pogoda/sydney",
                "окленд": "https://yandex.ru/pogoda/auckland", "нью-дели": "https://yandex.ru/pogoda/108944",
                "сингапур": "https://yandex.ru/pogoda/singapore", "дубай": "https://yandex.ru/pogoda/dubai",
                "стамбул": "https://yandex.ru/pogoda/istanbul", "воронеж": "https://yandex.ru/pogoda/voronezh",
                "краснодар": "https://yandex.ru/pogoda/krasnodar", "уфа": "https://yandex.ru/pogoda/ufa"}
